// Generated by https://quicktype.io

export interface JobOfferListRS {
  offerList: JobOffer[];
}

export interface JobOffer {
  createdAt: string;
  updatedAt: string;
  id: number;
  contractPeriod: string;
  requirements: string;
  salary: number;
  responsabilities: string;
  descriptionOffer: string;
  validDate: string;
  initWorkingDayTime: string;
  endWorkingDayTime: string;
  position: string;
  vacancyNumbers: number;
  enabled: boolean;
  business: Business;
}

export interface Business {
  id: number;
  name: string;
  aboutUs: string;
  email: string;
  enable: boolean;
}
